updated workflow

diff --git a/.github/workflows/pre_commit_test.yml b/.github/workflows/pre_commit_test.yml
--- a/.github/workflows/pre_commit_test.yml
+++ b/.github/workflows/pre_commit_test.yml
@@ -41,13 +41,14 @@ jobs:
           source venv/bin/activate
           cd tests/mock && make mock-db-location && make mock-db
       - name: Run Tests and Calculate Coverage
+        id: pytest
         run: |
           source venv/bin/activate
           echo -e "\npython_files = tests/unit/*" >> pytest.ini
           echo -e "filterwarnings = ignore::DeprecationWarning" >> pytest.ini
           pytest -m pre_commit > logs.txt
+          echo "::set-output name=status::success"
           coverage_percentage=$(coverage report -m | awk '/TOTAL/ {print $6}')
-          echo "Coverage Percentage: $coverage_percentage"
           echo "COVERAGE_PERCENTAGE=$coverage_percentage" >> $GITHUB_ENV
       - name: Upload Artifact
         uses: actions/upload-artifact@v3
@@ -57,6 +58,12 @@ jobs:
           retention-days: 5
       - name: Check threshold coverage
         run: |
+          if [ "${{ steps.pytest.outputs.status }}" != "success" ]; then
+            echo "Pytest failed."
+            exit 1
+          else
+            echo "Pytest passed."
+          fi
           echo "Coverage Percentage: $COVERAGE_PERCENTAGE"
           coverage=$(echo "$COVERAGE_PERCENTAGE" | sed 's/%//')
           if [ "$coverage" -lt 10 ]; then
